- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vector_config: /etc/vector/vector.yml
    vector_package: vector
  tasks:
    - name: Assert Vector instalation
      ansible.builtin.command: "vector --version"
      changed_when: false
      register: vector_version
      failed_when: vector_version.rc != 0
    - name: Validation Vector configuration
      ansible.builtin.command: "vector validate --no-environment {{ vector_config }}"
      register: vector_config_valid
      failed_when: vector_config_valid.rc != 0
      changed_when: false
